with PROJ.Tests.test_grids;
with PROJ.Tests.gie_self_tests;
with PROJ.Tests.test_operation;
with PROJ.Tests.test_util;
with PROJ.Tests.pj_transform_test;
with PROJ.Tests.test_io;
with PROJ.Tests.test_common;
with PROJ.Tests.test_crs;
with PROJ.Tests.test_factory;
with PROJ.Tests.proj_errno_string_test;
with PROJ.Tests.test_network;
with PROJ.Tests.test_datum;
with PROJ.Tests.pj_phi2_test;
with PROJ.Tests.test_metadata;
with PROJ.Tests.proj_angular_io_test;
with PROJ.Tests.proj_context_test;
with PROJ.Tests.test_c_api;
package body PROJ.Tests.Test_Suit is
   T_test_grids : aliased PROJ.Tests.test_grids.Test_Case;
   T_gie_self_tests : aliased PROJ.Tests.gie_self_tests.Test_Case;
   T_test_operation : aliased PROJ.Tests.test_operation.Test_Case;
   T_test_util : aliased PROJ.Tests.test_util.Test_Case;
   T_pj_transform_test : aliased PROJ.Tests.pj_transform_test.Test_Case;
   T_test_io : aliased PROJ.Tests.test_io.Test_Case;
   T_test_common : aliased PROJ.Tests.test_common.Test_Case;
   T_test_crs : aliased PROJ.Tests.test_crs.Test_Case;
   T_test_factory : aliased PROJ.Tests.test_factory.Test_Case;
   T_proj_errno_string_test : aliased PROJ.Tests.proj_errno_string_test.Test_Case;
   T_test_network : aliased PROJ.Tests.test_network.Test_Case;
   T_test_datum : aliased PROJ.Tests.test_datum.Test_Case;
   T_pj_phi2_test : aliased PROJ.Tests.pj_phi2_test.Test_Case;
   T_test_metadata : aliased PROJ.Tests.test_metadata.Test_Case;
   T_proj_angular_io_test : aliased PROJ.Tests.proj_angular_io_test.Test_Case;
   T_proj_context_test : aliased PROJ.Tests.proj_context_test.Test_Case;
   T_test_c_api : aliased PROJ.Tests.test_c_api.Test_Case;

    S : aliased AUnit.Test_Suites.Test_Suite;
    
   function Suit return AUnit.Test_Suites.Access_Test_Suite is
   begin
      S.Add_Test(T_test_grids'Access);
      S.Add_Test(T_gie_self_tests'Access);
      S.Add_Test(T_test_operation'Access);
      S.Add_Test(T_test_util'Access);
      S.Add_Test(T_pj_transform_test'Access);
      S.Add_Test(T_test_io'Access);
      S.Add_Test(T_test_common'Access);
      S.Add_Test(T_test_crs'Access);
      S.Add_Test(T_test_factory'Access);
      S.Add_Test(T_proj_errno_string_test'Access);
      S.Add_Test(T_test_network'Access);
      S.Add_Test(T_test_datum'Access);
      S.Add_Test(T_pj_phi2_test'Access);
      S.Add_Test(T_test_metadata'Access);
      S.Add_Test(T_proj_angular_io_test'Access);
      S.Add_Test(T_proj_context_test'Access);
      S.Add_Test(T_test_c_api'Access);
      return s'access;
   end Suit;
end PROJ.Tests.Test_Suit;
